version: '3.5'
services:
  frontend:
    container_name: arkham_bag_simulator_frontend
    restart: always
    build: ./frontend
    ports: 
        - 8080:80
    # volumes:
    #   - ./:/code
    # stdin_open: true
    # tty: true
  backend:
    container_name: arkham_bag_simulator_backend
    restart: always
    depends_on:
      - db
    links:
      - db
    build: ./backend
    ports: 
        - 8000:80
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  # queue:
  #   image: rabbitmq:latest