version: '3.5'
services:
  frontend:
    container_name: abs_frontend
    restart: always
    build: 
        context: ./frontend
        dockerfile: Dockerfile-dev
    ports: 
        - 8080:8080
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "serve"]
  backend:
    container_name: abs_backend
    restart: always
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    build: 
        context: ./backend
    ports: 
        - 8000:80
    volumes:
      - ./backend/app:/app
    entrypoint:
      - /start-reload.sh
    stdin_open: true
    tty: true
  db:
    container_name: abs_db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
        - adb_pg_db_dev:/var/lib/postgresql/data
  redis:
    container_name: abs_redis
    image: redis:alpine
volumes:
  adb_pg_db_dev:
  